# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20160629_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='category_id',
            new_name='category',
        ),
    ]
